# Case-fatality rate of SARS-2-CoV and other viruses
Statistics from SARS-2-CoV from https://github.com/cmrivers/ncov/blob/master/COVID-19.pdf:

In [4]:
import pandas as pd

sars2 = pd.DataFrame.from_records(
            [('0-9', 5, 0),
             ('10-19', 15, 0.2),
             ('20-29', 25, 0.2),
             ('30-39', 35, 0.2),
             ('40-49', 45, 0.4),
             ('50-59', 55, 1.3),
             ('60-69', 65, 3.6),
             ('70-79', 75, 8.0),
             ('>80', 85, 14.8)],
            columns=['label', 'age', 'case fatality rate (%)'])
sars2

   label  age  case fatality rate (%)
0    0-9    5                     0.0
1  10-19   15                     0.2
2  20-29   25                     0.2
3  30-39   35                     0.2
4  40-49   45                     0.4
5  50-59   55                     1.3
6  60-69   65                     3.6
7  70-79   75                     8.0
8    >80   85                    14.8

Statistics for 1918 influenza apparently from [Public Health Reports, 34:1832-1861 (1919)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1996932/pdf/pubhealthreporig02734-0001.pdf), but I just guess-timated numbers from [Figure 3 of Emerging Infectious Diseases, 12:1 (2006)](https://wwwnc.cdc.gov/eid/article/12/1/05-0979-f3)

In [5]:
flu1918 = pd.DataFrame.from_records(
            [('0-1', 1, 5.2),
             ('2-5', 2.5, 1.6),
             ('5-10', 7.5, 0.5),
             ('10-15', 12.5, 0.6),
             ('15-20', 17.5, 1.1),
             ('20-25', 22.5, 1.8),
             ('25-30', 27.5, 3.0),
             ('30-35', 32.5, 2.5),
             ('35-40', 37.5, 2.4),
             ('40-45', 42.5, 1.8),
             ('45-50', 47.5, 1.3),
             ('50-55', 52.5, 1.8),
             ('55-60', 57.5, 1.2),
             ('60-65', 62.5, 3.1),
             ('65-70', 67.5, 4.2),
             ('70-75', 72.5, 5.2)
             ],
            columns=['label', 'age', 'case fatality rate (%)'])
flu1918

    label   age  case fatality rate (%)
0     0-1   1.0                     5.2
1     2-5   2.5                     1.6
2    5-10   7.5                     0.5
3   10-15  12.5                     0.6
4   15-20  17.5                     1.1
5   20-25  22.5                     1.8
6   25-30  27.5                     3.0
7   30-35  32.5                     2.5
8   35-40  37.5                     2.4
9   40-45  42.5                     1.8
10  45-50  47.5                     1.3
11  50-55  52.5                     1.8
12  55-60  57.5                     1.2
13  60-65  62.5                     3.1
14  65-70  67.5                     4.2
15  70-75  72.5                     5.2

Statistics for seasonal influenza from 1997 to 2007 taken from Table 1 of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3873104/ assuming a 10% incidence rate:

In [12]:
flu_1997to2007 = pd.DataFrame.from_records(
            [('<18', 9, 0.41 / 1e3 / 0.1),
             ('18-49', 33, 1.03 / 1e3 / 0.1),
             ('50-64', 57, 7.18 / 1e3 / 0.1),
             ('65-74', 70, 26.37 / 1e3 / 0.1),
             ('>75', 80,141.15 / 1e3 / 0.1)
             ],
            columns=['label', 'age', 'case fatality rate (%)'])

flu_1997to2007

   label  age  case fatality rate (%)
0    <18    9                  0.0041
1  18-49   33                  0.0103
2  50-64   57                  0.0718
3  65-74   70                  0.2637
4    >75   80                  1.4115

In [14]:
df = pd.concat([
        sars2.assign(virus='SARS-2 CoV'),
        flu1918.assign(virus='1918 influenza'),
        flu_1997to2007.assign(virus='influenza 1997-2007')
        ])

df

    label   age  case fatality rate (%)                virus
0     0-9   5.0                  0.0000           SARS-2 CoV
1   10-19  15.0                  0.2000           SARS-2 CoV
2   20-29  25.0                  0.2000           SARS-2 CoV
3   30-39  35.0                  0.2000           SARS-2 CoV
4   40-49  45.0                  0.4000           SARS-2 CoV
5   50-59  55.0                  1.3000           SARS-2 CoV
6   60-69  65.0                  3.6000           SARS-2 CoV
7   70-79  75.0                  8.0000           SARS-2 CoV
8     >80  85.0                 14.8000           SARS-2 CoV
0     0-1   1.0                  5.2000       1918 influenza
1     2-5   2.5                  1.6000       1918 influenza
2    5-10   7.5                  0.5000       1918 influenza
3   10-15  12.5                  0.6000       1918 influenza
4   15-20  17.5                  1.1000       1918 influenza
5   20-25  22.5                  1.8000       1918 influenza
6   25-30  27.5                  3.0000       1918 influenza
7   30-35  32.5                  2.5000       1918 influenza
8   35-40  37.5                  2.4000       1918 influenza
9   40-45  42.5                  1.8000       1918 influenza
10  45-50  47.5                  1.3000       1918 influenza
11  50-55  52.5                  1.8000       1918 influenza
12  55-60  57.5                  1.2000       1918 influenza
13  60-65  62.5                  3.1000       1918 influenza
14  65-70  67.5                  4.2000       1918 influenza
15  70-75  72.5                  5.2000       1918 influenza
0     <18   9.0                  0.0041  influenza 1997-2007
1   18-49  33.0                  0.0103  influenza 1997-2007
2   50-64  57.0                  0.0718  influenza 1997-2007
3   65-74  70.0                  0.2637  influenza 1997-2007
4     >75  80.0                  1.4115  influenza 1997-2007

In [32]:
from plotnine import *

from alignparse.constants import CBPALETTE

p = (ggplot(df, aes('age', 'case fatality rate (%)', color='virus', shape='virus')) +
     geom_line() +
     geom_point(size=2) +
     scale_color_manual(values=CBPALETTE[1:]) +
     theme(figure_size=(3.5, 2.25))
     )
p.save('cfr.pdf')

/Users/jbloom/opt/miniconda3/lib/python3.7/site-packages/plotnine/ggplot.py:729: PlotnineWarning: Saving 3.5 x 2.25 in image.
  from_inches(height, units), units), PlotnineWarning)
/Users/jbloom/opt/miniconda3/lib/python3.7/site-packages/plotnine/ggplot.py:730: PlotnineWarning: Filename: cfr.pdf
  warn('Filename: {}'.format(filename), PlotnineWarning)